export function observasiPasca() {
    return [
        {
            model: 'bolus',
            td1: "T0 (Bolus)",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 1
        {
            model: 'jamKe_1_15',
            td1: "Jam ke-1",
            td2: "15",
            colspan: false,
            rowspan: true,
            jumlahcolspan: 0,
            jumlahrowspan: 4,
        },
        {
            model: 'jamKe_1_30',
            td1: "",
            td2: "30",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        {
            model: 'jamKe_1_45',
            td1: "",
            td2: "45",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        {
            model: 'jamKe_1_60',
            td1: "",
            td2: "60",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        //jam ke 2
        {
            model: 'jamKe_2_15',
            td1: "Jam ke-2",
            td2: "15",
            colspan: false,
            rowspan: true,
            jumlahcolspan: 0,
            jumlahrowspan: 4,
        },
        {
            model: 'jamKe_2_30',
            td1: "",
            td2: "30",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        {
            model: 'jamKe_2_45',
            td1: "",
            td2: "45",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        {
            model: 'jamKe_2_60',
            td1: "",
            td2: "60",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        // jam ke-3
        {
            model: 'jamKe_3_30',
            td1: "Jam ke-3",
            td2: "30",
            colspan: false,
            rowspan: true,
            jumlahcolspan: 0,
            jumlahrowspan: 2,
        },
        {
            model: 'jamKe_3_60',
            td1: "",
            td2: "60",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        // jam ke-4
        {
            model: 'jamKe_4_30',
            td1: "Jam ke-4",
            td2: "30",
            colspan: false,
            rowspan: true,
            jumlahcolspan: 0,
            jumlahrowspan: 2,
        },
        {
            model: 'jamKe_4_60',
            td1: "",
            td2: "60",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        // jam ke-5
        {
            model: 'jamKe_5_30',
            td1: "Jam ke-5",
            td2: "30",
            colspan: false,
            rowspan: true,
            jumlahcolspan: 0,
            jumlahrowspan: 2,
        },
        {
            model: 'jamKe_5_60',
            td1: "",
            td2: "60",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        // jam ke-6
        {
            model: 'jamKe_6_30',
            td1: "Jam ke-6",
            td2: "30",
            colspan: false,
            rowspan: true,
            jumlahcolspan: 0,
            jumlahrowspan: 2,
        },
        {
            model: 'jamKe_6_60',
            td1: "",
            td2: "60",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        // jam ke-7
        {
            model: 'jamKe_7_30',
            td1: "Jam ke-7",
            td2: "30",
            colspan: false,
            rowspan: true,
            jumlahcolspan: 0,
            jumlahrowspan: 2,
        },
        {
            model: 'jamKe_7_60',
            td1: "",
            td2: "60",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        // jam ke-8
        {
            model: 'jamKe_8_30',
            td1: "Jam ke-8",
            td2: "30",
            colspan: false,
            rowspan: true,
            jumlahcolspan: 0,
            jumlahrowspan: 2,
        },
        {
            model: 'jamKe_8_60',
            td1: "",
            td2: "60",
            colspan: false,
            rowspan: false,
            jumlahcolspan: 0,
            jumlahrowspan: 0,
        },
        //jam ke 10
        {
            model: 'jamKe_10',
            td1: "Jam ke-10",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 11
        {
            model: 'jamKe_11',
            td1: "Jam ke-11",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 12
        {
            model: 'jamKe_12',
            td1: "Jam ke-12",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 13
        {
            model: 'jamKe_13',
            td1: "Jam ke-13",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 14
        {
            model: 'jamKe_14',
            td1: "Jam ke-14",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 15
        {
            model: 'jamKe_15',
            td1: "Jam ke-15",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 16
        {
            model: 'jamKe_16',
            td1: "Jam ke-16",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 17
        {
            model: 'jamKe_17',
            td1: "Jam ke-17",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 18
        {
            model: 'jamKe_18',
            td1: "Jam ke-18",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 19
        {
            model: 'jamKe_19',
            td1: "Jam ke-19",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 20
        {
            model: 'jamKe_20',
            td1: "Jam ke-20",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 21
        {
            model: 'jamKe_21',
            td1: "Jam ke-21",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 23
        {
            model: 'jamKe_23',
            td1: "Jam ke-23",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //jam ke 24
        {
            model: 'jamKe_24',
            td1: "Jam ke-24",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //hari ke 2
        {
            model: 'hariKe_2',
            td1: "Hari ke-2",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //hari ke 3
        {
            model: 'hariKe_3',
            td1: "Hari ke-3",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //hari ke 4
        {
            model: 'hariKe_4',
            td1: "Hari ke-4",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
        //hari ke 5
        {
            model: 'hariKe_5',
            td1: "Hari ke-5",
            td2: "",
            colspan: true,
            rowspan: false,
            jumlahcolspan: 2,
            jumlahrowspan: 0,
        },
    ]
}